version: '3'

networks:
  safwat-task:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8070:80"
    volumes:
      - app-data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - safwat-task

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - app-data:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - safwat-task
    entrypoint: ["sh", "-c", "chown -R www-data:www-data /var/www/html/storage && php-fpm"]

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: php-test
    volumes:
      - app-data:/var/www/html
    networks:
      - safwat-task
    command: ["vendor/bin/phpunit"]

volumes:
  app-data: